scopes:

    enabled:
        label: Enabled
        type: switch
        conditions:
            - is_enabled <> true
            - is_enabled = true

    visible:
        label: Visible
        type: switch
        conditions:
            - is_visible <> true
            - is_visible = true

    available:
        label: Available
        type: switch
        conditions:
            - is_available = 0 || (is_available = 2 && available_at > NOW())
            - is_available = 1 || (is_available = 2 && available_at < NOW())
