# Model List Column configuration
list: $/octoshop/core/models/product/columns.yaml

# List filter configuration
filter: config_filter.yaml

# Model Class name
modelClass: Octoshop\Core\Models\Product

# List Title
title: Manage Products

# Link URL for each record
recordUrl: octoshop/core/products/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
